"""migration3

Revision ID: ec279ceddcc7
Revises: 4ef4bd2e37db
Create Date: 2025-01-19 16:01:40.368940

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ec279ceddcc7"
down_revision: Union[str, None] = "4ef4bd2e37db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=20), nullable=False))
    op.drop_column("users", "login")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("login", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    )
    op.drop_column("users", "username")
    # ### end Alembic commands ###
